#define NO_TESTS 10000

#define COLL_CHECK 1
#define DO_PRINT 1

#define DO_ATTACK 1
#define M_VALUE 0
#define N_VALUE 4

#define GAP_THRESHOLD_1_1 60
#define GAP_THRESHOLD_1_2 60

#define GAP_THRESHOLD_2_1 105
#define GAP_THRESHOLD_2_2 105

#define C_VALUE_THRESHOLD_1 130
#define C_VALUE_THRESHOLD_2 130

#define C_VALUE_THRESHOLD_1_TRIMMER 5
#define C_VALUE_THRESHOLD_2_TRIMMER 80

#define C_VALUE_THRESHOLD_1_TRIMMER_LESS 20
#define C_VALUE_THRESHOLD_1_TRIMMER_GREAT 40
